#!/bin/bash

function run {
  if ! pgrep $1 ;
  then
    $@&
  fi
}

function MainMenu(){
    options=()
        options+=("1" "System")
        options+=("2" "Beginner Guide")
        options+=("3" "Package Info")
        options+=("4" "Configuration")
        options+=("5" "Arch Linux")
        options+=("6" "Others")
        options+=("7" "Exit")
    help=$(whiptail --backtitle "Calinix Help Menu" --title "Main Menu" --menu "" 0 0 0 \
            "${options[@]}" \
            3>&1 1>&2 2>&3)
    if [ "$?" = "0" ]; then
		case ${help} in
            "1")
               systemMenu 
            ;;
            "2")
                beginnerGuide
            ;;
        esac
    fi
}

systemMenu(){
    options=()
        options+=("1" "Update your System")
        options+=("2" "Update your Repositories")
        options+=("3" "Clear Package Cache")
        options+=("4" "Change your Shell")
        options+=("5" "Install a Different Kernel")
        options+=("6" "(By untergrundbiber)")
        options+=("7" "(By quelotic)")
        options+=("8" "(By thegoldgoat)")
        options+=("9" "(By KardiWeb)")
        options+=("10" "(By mrboen94)")
        options+=("11" "(By dawidd6)")
        options+=("12" "(By hugok)")
        options+=("13" "(By Anonymous_Prodject)")
        options+=("14" "(By Mystogab)")
        options+=("15" "(By c0b41)")
    help=$(whiptail --backtitle "System-Related Tweaks" --title "System" --menu "" 0 0 0 \
            "${options[@]}" \
            3>&1 1>&2 2>&3)
    if [ "$?" = "0" ]; then
		case ${help} in
            "1")
                whiptail --msgbox --title "WARNING" "Don't stop or interrupt an update in between, Let it happen. Interrupting may damage dependencies or worse, break your system" 10 50
                tput setaf 2; echo "Updating your whole system...\n"
                sudo pacman -Syu --noconfirm
                whiptail --msgbox --title "Finished" "System was Updated" 10 50
            ;;
            "2")
                tput setaf 2; echo "Updating your repositories...\n"
                sudo pacman -Syy --noconfirm
                whiptail --msgbox --title "Finished" "The Repositories was Updated" 10 50
            ;;
            "3")
                whiptail --msgbox --title "INFO" "This is usually done when you face the following error:\n\nFailed to init transaction (unable to lock database)\n\nClearing the db lock usually fixes this error" 10 50
                tput setaf 2; echo "Clearing Pacman Cache...\n"
                sudo pacman -Sc --noconfirm
                whiptail --msgbox --title "Finished" "Cache Deleted" 10 50
            ;;
            "4")
                changeShell
            ;;
            "5")
                installKernel
            ;;
            "1")
                whiptail --msgbox --title "WARNING" "Don't stop or interrupt an update in between, Let it happen. Interrupting may damage dependencies or worse, break your system" 10 50
                tput setaf 2; echo "Updating your whole system...\n"
                sudo pacman -Syu --noconfirm
                whiptail --msgbox --title "Finished" "System was Updated" 10 50
            ;;
        esac
    fi
}

changeShell(){
    options=()
        options+=("1" "Bash")
        options+=("2" "Zsh")
        options+=("3" "Fish")
    shn=$(whiptail --title "Shell" --menu "" 0 0 0 \
            "${options[@]}" \
            3>&1 1>&2 2>&3)
    if [ "$?" = "0" ]; then
		case ${shn} in
            "1")
                tput setaf 2; echo "Changing shell to ${shn}...\n"
                sudo pacman -Sy bash --needed
                sudo chsh $USER -s /bin/bash && echo 'Now log out.'
                whiptail --msgbox --title "Finished" "Shell changed to ${shn}" 10 50
            ;;
            "2")
                tput setaf 2; echo "Changing shell to ${shn}...\n"
                 sudo pacman -Sy zsh --needed
                 sudo chsh $USER -s /bin/zsh && echo 'Now log out.'
                whiptail --msgbox --title "Finished" "Shell changed to ${shn}" 10 50
            ;;
            "3")
                tput setaf 2; echo "Changing shell to ${shn}...\n"
                 sudo pacman -Sy fish --needed
                 sudo chsh $USER -s /bin/fish && echo 'Now log out.'
                whiptail --msgbox --title "Finished" "Shell changed to ${shn}" 10 50
            ;;
        esac
fi
}

installKernel(){
    options=()
        options+=("linux" "The standard linux kernel with latest updates (Default)")
        options+=("linux-lts" "The LTS kernel with less frequent updates.")
        options+=("linux-zen" "A kernel made for improving performance and providing best linux desktop experience")
        options+=("linux-hardened" "A security focused kernel with some tweaks.")
        options+=("linux-xanmod-lts" "A super performant kernel based on linux-zen. Suitable for gaming and performance centric work.")
    shn=$(whiptail --title "Kernel" --menu "" 0 0 0 \
            "${options[@]}" \
            3>&1 1>&2 2>&3)
    if [ "$?" = "0" ]; then
		yay -S $shn ${shn}-headers --noconfirm
        whiptail --msgbox --title "Finished" "Installed Kernel ${shn}" 10 50
fi
}

beginnerGuide(){
    options=()
        options+=("1" "A Gentle Introduction To Linux")
        options+=("2" "Reasons to Run Arch Linux")
        options+=("3" "The Pacman Package Manager for Arch Linux")
        options+=("4" "How to Learn Linux?")
        options+=("5" "How to get more comfortable in Linux than Windows/OSX?")
        options+=("6" "Mistakes New Linux Users make")
        options+=("7" "Beginner's Guide To Linux Terminal")
        options+=("8" "Introduction to Alacritty Terminal Emulator")
        options+=("9" "Beginner's Guide to GIMP")
        options+=("10" "Ultimate Guide to Yay")
        options+=("11" "A comprehensive guide to Tiling Window Managers")
        options+=("12" "Why Use A Tiling Window Manager?")
        options+=("13" "F.A.Q for Tiling WIndow Managers")
        options+=("14" "Make Arch Linux a bit more Stable")
        options+=("15" "Terminal Disk Utilities in Arch Linux")
        options+=("16" "Beginner's Guide to Zsh")
        options+=("17" "What are Linux Desktop Environments")
        options+=("18" "Vim tutorial by Ben Awad")
        options+=("19" "")
        options+=("20" "")
        options+=("21" "")
        options+=("22" "")
        options+=("23" "")
        options+=("24" "")
    shn=$(whiptail --title "Kernel" --menu "" 0 0 0 \
            "${options[@]}" \
            3>&1 1>&2 2>&3)
    if [ "$?" = "0" ]; then
        case ${shn} in
            1)
                run xdg-open "https://www.youtube.com/watch?v=G4C2pMVTxao"
                ;;
            2)
                run xdg-open "https://www.youtube.com/watch?v=8RqFL92IEYs"
                ;;
            3)
                run xdg-open "https://www.youtube.com/watch?v=-UvZ4BEAXFU"
                ;;
            4)
                run xdg-open "https://www.youtube.com/watch?v=a2qblT7o4mE"
                ;;
            5)
                run xdg-open "https://www.youtube.com/watch?v=fWHKAn5W2CA"
                ;;
            6)
                run xdg-open "https://www.youtube.com/watch?v=mkrN4uAcDGk"
                ;;
            7)
                run xdg-open "https://www.youtube.com/watch?v=s3ii48qYBxA"
                ;;
            8)
                run xdg-open "https://www.youtube.com/watch?v=PZPMvTvUf1Y1"
                ;;
            9)
                run xdg-open "https://www.youtube.com/watch?v=YHwnlgD18kE"
                ;;
            10)
                run xdg-open "https://www.youtube.com/watch?v=BbnSoY_yDr8&t=137s"
                ;;
            11)
                run xdg-open "https://www.youtube.com/watch?v=Obzf9ppODJU"
                ;;
            12)
                run xdg-open "https://www.youtube.com/watch?v=Lj1IfdKY0CU"
                ;;
            13)
                run xdg-open "https://www.youtube.com/watch?v=Qauypve7zbY"
                ;;
            14)
                run xdg-open "https://www.youtube.com/watch?v=xhVS1HKwGWw"
                ;;
            15)
                run xdg-open "https://www.youtube.com/watch?v=jrUcdVgTmZ4"
                ;;
            16)
                run xdg-open "https://www.youtube.com/watch?v=MSPu-lYF-A8"
                ;;
            17)
                run xdg-open "https://www.youtube.com/watch?v=2sBsxrWD9to"
                ;;
            18)
                run xdg-open "https://youtu.be/IiwGbcd8S7I"
                ;;
            19)
                run xdg-open ""
                ;;
            20)
                run xdg-open ""
                ;;
            21)
                run xdg-open ""
                ;;
            22)
                run xdg-open ""
                ;;
            23)
                run xdg-open ""
                ;;
            24)
                run xdg-open ""
                ;;
            25)
                run xdg-open ""
                ;;
            26)
                run xdg-open ""
                ;;
            27)
                run xdg-open ""
                ;;
            28)
                run xdg-open ""
                ;;
            29)
                run xdg-open ""
                ;;
            30)
                run xdg-open ""
                ;;
            31)
                run xdg-open ""
                ;;
            
        esac
fi
}


MainMenu
# systemMenu